#Provisions the infra creation requests on Google Cloud Platform

name: Provision the AI Agent

on:
# Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
  # This workflow contains a single job called "build"
  process_provisioning_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    permissions:
        contents: read
        id-token: write

        
    steps:
        - name: Capture Job Start Time
          id: start
          run: |
            echo "JOBSTARTTIME=$(date --utc --iso-8601=seconds)" >> $GITHUB_OUTPUT

        - name: Clone the directory
          uses: actions/checkout@v2

        - id: auth
          name: Authenticate To Google Cloud
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: 'projects/351592443/locations/global/workloadIdentityPools/identity-pool-2/providers/da-idp'
            service_account: '${{ secrets.SERVICE_ACCOUNT }}'
            project_id: '${{ secrets.PROJECT_ID }}'


        - name: Setup Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
  
        - name: Use gcloud CLI
          run: gcloud info

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.7.5

        - name: Get request details from DB & store it in Shell variables
          id: post_data
          run: |
            echo "ID=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].id")" >> $GITHUB_OUTPUT
            echo "COMPONENTS=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].components")" >> $GITHUB_OUTPUT
            echo "RESOURCE_EXPIRY_TIME=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].expirytime")" >> $GITHUB_OUTPUT
            echo $ID
            echo $COMPONENTS
            echo $RESOURCE_EXPIRY_TIME

            
        - name: Trigger Build & Deploy
          run: |
            echo ${{ steps.post_data.outputs.ID }}
            cd ${{ steps.post_data.outputs.COMPONENTS }}
            pwd
            ls
            gcloud run deploy ${{ steps.post_data.outputs.ID }} --source . --region us-central1 --project eternal-argon-461501-a8 --allow-unauthenticated --set-env-vars="GOOGLE_CLOUD_PROJECT=eternal-argon-461501-a8,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_GENAI_USE_VERTEXAI=True"

        - name: Update Provisioned Table
          run: |
            curl "http://"${{ secrets.POSTGRES_IP }}"/PROVISIONED" -X POST -H "Content-Type: application/json"  -d "{\"id\": \"${{ steps.post_data.outputs.ID }}\", \"jobstarttime\": \"${{ steps.start.outputs.JOBSTARTTIME }}\", \"jobendtime\": \"$(date --utc --iso-8601=seconds)\" , \"joboutput\": \"abcpqrxyz\",\"resourceexpirytime\":\"${{ steps.post_data.outputs.RESOURCE_EXPIRY_TIME }}\"}"
