#Provisions the infra creation requests on Google Cloud Platform

name: Provision the Infrastructure

on:
# Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  process_provisioning_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
        
    steps:
        - name: Get request details from DB & store it in Shell variables
          id: post_data
          run: |
            echo "ID=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDING | jq -r ".[0].id")" >> $GITHUB_OUTPUT
            echo "COMPONENTS=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDING | jq -r ".[0].components")" >> $GITHUB_OUTPUT
            echo "RESOURCE_EXPIRY_TIME=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDING | jq -r ".[0].expirytime")" >> $GITHUB_OUTPUT
            echo $ID
            echo $COMPONENTS
            echo $RESOURCE_EXPIRY_TIME
            

        - name: Clone the TF templates directory
          uses: actions/checkout@v4

        - name: Prepare terraform files
          run: |
            echo ${{ steps.post_data.outputs.ID }}
            cd terraform_templates
            sed -i "s/request_id/${{ steps.post_data.outputs.ID }}/g" main.tf
            IFS=','
            read -ra mod_array <<< "$COMPONENTS"
            for element in "${mod_array[@]}"; do
              cat references/"$element".txt >> main.tf
            done

        - name: Apply Terraform
          run: |
            terraform init
            terraform plan
            terraform apply -auto-approve








