#Provisions the infra creation requests on Google Cloud Platform

name: Provision the AI Agent

on:
# Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
  # This workflow contains a single job called "build"
  process_agent_provisioning_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    permissions:
        contents: read
        id-token: write

        
    steps:
        - name: Capture Job Start Time
          id: start
          run: |
            echo "JOBSTARTTIME=$(date --utc --iso-8601=seconds)" >> $GITHUB_OUTPUT

        - name: Clone the directory
          uses: actions/checkout@v4

        - id: auth
          name: Authenticate To Google Cloud
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: 'projects/351592443/locations/global/workloadIdentityPools/identity-pool-2/providers/da-idp'
            service_account: '${{ secrets.SERVICE_ACCOUNT }}'
            project_id: '${{ secrets.PROJECT_ID }}'


        - name: Setup Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
            version: '>= 528.0.0'
  
        - name: Use gcloud CLI
          run: gcloud info

        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install google-adk



         #name: Debugging Session with Tmate
         #uses: mxschmitt/action-tmate@v3    
       

        - name: Get request details from DB & store it in Shell variables
          id: post_data
          run: |
            echo "ID=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].id")" >> $GITHUB_OUTPUT
            echo "COMPONENTS=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].components")" >> $GITHUB_OUTPUT
            echo "RESOURCE_EXPIRY_TIME=$(curl http://"${{ secrets.POSTGRES_IP }}"/PENDINGAGENTCREATION | jq -r ".[0].expirytime")" >> $GITHUB_OUTPUT
            echo $ID
            echo $COMPONENTS
            echo $RESOURCE_EXPIRY_TIME

            
        - name: Trigger Build & Deploy
          run: |
            
            NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 8)
            echo $NAME
            cd financial_advisor_team
            export GOOGLE_CLOUD_PROJECT=eternal-argon-461501-a8
            export GOOGLE_CLOUD_LOCATION=us-central1
            export GOOGLE_GENAI_USE_VERTEXAI=True
            export SERVICE_NAME=service-${NAME}
            export APP_NAME=fa-app-${NAME}
            export AGENT_PATH=./financial_advisor

            adk deploy cloud_run --project=$GOOGLE_CLOUD_PROJECT --region=$GOOGLE_CLOUD_LOCATION --service_name=$SERVICE_NAME --app_name=$APP_NAME --with_ui $AGENT_PATH
            cat Dockerfile
            
        - name: Update Provisioned Table
          run: |
            curl "http://"${{ secrets.POSTGRES_IP }}"/PROVISIONEDINFRA" -X POST -H "Content-Type: application/json"  -d "{\"id\": \"${{ steps.post_data.outputs.ID }}\", \"jobstarttime\": \"${{ steps.start.outputs.JOBSTARTTIME }}\", \"jobendtime\": \"$(date --utc --iso-8601=seconds)\" , \"joboutput\": \"abcpqrxyz\",\"resourceexpirytime\":\"${{ steps.post_data.outputs.RESOURCE_EXPIRY_TIME }}\"}"
