# This is a basic workflow to help you get started with Actions

name: Insert Requests from Backstage Details into Postgres Database

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      agent_identifier_name:
        description: 'Agent Name'
        required: true

      components:
        description: 'Components'
        required: true


      agent_action:
        description: 'Agent Action'
        required: true



      duration:
        description: 'Infra life in days'
        required: true

        
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  accept_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Initialize Variables
        run: |
          export UNIQUE_ID=$(uuidgen)
          export TIMESTAMP_TZ=$(date --u --iso-8601=seconds)
          export EXPIRY_TIME=$(date --u -d "+${duration} days" --iso-8601=seconds)
          echo "$UNIQUE_ID"
          echo "$TIMESTAMP_TZ"
          echo "$EXPIRY_TIME"




      - name: Make the HTTP POST request
        run: |
          curl "http://24.46.107.64:7080/REQUESTED" -X POST -H "Content-Type: application/json"  -d "{\"id\": \"$(uuidgen)\", \"components\": \"${{ github.event.inputs.components }}\", \"requestedtime\": \"$(date -u --iso-8601=seconds)\" , \"expirytime\": \"$(date -u --iso-8601=seconds -d "+10 days")\"}"


      #- name: Debugging Session with Tmate
      #  uses: mxschmitt/action-tmate@v3    
      # Runs a set of commands using the runners shell